[package]
name = "fpl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.10", features = ["derive"] }
csv = "1.2.2"
html-escape = "0.2.13"
nom = "7.1.3"
serde = { version = "1.0.164", features = ["derive"] }
